version: '3.8'
services:
  admin-web:
    build:
      context: ./scib-admin
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3001:80"
    networks:
      - network1
  web:
    build:
      context: ./scib-web
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:80"
    networks:
      - network1
  api:
    build:
      context: ./scib-svr
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - ftp
    ports:
      - "80:80"
    environment:
      - "PORT=80"
    networks:
      - network1
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - "USERS=scib|bics"
      - "ADDRESS=0.0.0.0"
    restart: on-failure
    networks:
      - network1

volumes:
  mongodata:
  imagedata:

networks:
  network1:
    driver: bridge